### ISSUE TITLE
Episode 54 - Super Duper Gamers with Super Heroes! 

### ISSUE THREAD

**Issue by GamersOver50Podcast** [GamersOver50Podcast/Podcast#55]
https://en.wikipedia.org/wiki/Injustice:_Gods_Among_Us
https://en.wikipedia.org/wiki/Marvel:_Ultimate_Alliance
https://en.wikipedia.org/wiki/City_of_Heroes
https://en.wikipedia.org/wiki/Teenage_Mutant_Ninja_Turtles_(arcade_game)

**Comment by Malchian** [comment]
Published 10/5/21
